sudo: required
os: osx
osx_image: xcode9.3
language: ruby
rvm:
  - 2.5.0
before_install:
  - gem install bundler -v 1.16.1
  - brew update
  - brew tap simple2d/tap
  - brew install simple2d mruby
script:
  - bundle install && rake
